version: '3'

volumes:
  db-data:

services:
  db:
    image: postgres:14
    container_name: auth-with-query-lang
    volumes:
      - db-data:/var/lib/postgresql/auth-with-query-lang/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
