name: 'Run Lint CI'

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: 'read'

jobs:
  run-lint:
    name: lint

    timeout-minutes: 10

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set legacy-peer-deps
        run: npm config set legacy-peer-deps true

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint
